<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PickupRentalOfficeSuggestion</name>
   <tag></tag>
   <elementGuidId>45dbb81e-0a3b-40d0-a673-a6b3bc1c1f48</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;RENTAL_PICKUP_LOCATION&quot;]/div/div/div[3]/div[2]/div/div/div[1]/div[1]/div/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
