<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PickupRentalOfficeSuggetSelect</name>
   <tag></tag>
   <elementGuidId>f403271a-9916-47f0-941d-08569f10a714</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;RENTAL_PICKUP_LOCATION&quot;]/div/div/div[3]/div[2]/div/div/div[1]/div[2]/div/div/div/div[1]/div[1]/div/div[1]/div/div[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
